---
# Use Ubuntu 14.04 LTS images, and explicitly require sudo.
# Relevant docs: https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required
dist: trusty

language: python
python:
  - '2.7'

virtualenv:
  system_site_packages: true
before_install:
  - 'for e in /.packer-env/*; do echo -n "${e}: "; cat "${e}"; done'
  - sudo apt-get update -qq
  - sudo apt-get install --yes rng-tools
  - sudo rm -f /dev/random
  - sudo mknod -m 0666 /dev/random c 1 9
  - echo HRNGDEVICE=/dev/urandom | sudo tee /etc/default/rng-tools
  - sudo /etc/init.d/rng-tools restart
install:
  - pip freeze -l
  # Preinstalled travis pytest is not tracked by us
  - pip uninstall pytest -y
  - pip install -r testinfra/requirements.txt
script:
  # Using YAML folding operator '>' to aid in readability and avoid
  # extremely long lines.
  - >
      printf
      "[development]\nlocalhost\n[travis]\n[development:children]\ntravis"
      > inventory
  - >
      ansible-playbook -i inventory -vv --syntax-check
      install_files/ansible-base/securedrop-travis.yml
  - >
      ansible-playbook -i inventory -vv --connection=local
      --sudo --skip-tags=non-development
      install_files/ansible-base/securedrop-travis.yml

  # For some reason, redis-server does not start automatically when installed
  # on Travis. I believe Travis' service machinery may be interfering. See
  # http://docs.travis-ci.com/user/database-setup/#Redis
  - sudo service redis-server start
  # Travis needs the config.py file to be owned by root. In other environments
  # it's the `securedrop_user` var.
  - sudo chown root:root securedrop/config.py
  - sudo sh -c "export DISPLAY=:1; cd securedrop/ && pytest tests/"
  - ./testinfra/test.py
  # Docs linting. Performing this step *after* build VM tests pass, so as not
  # to alter the pip requirements, which would cause config tests to fail.
  - pip install -r securedrop/requirements/develop-requirements.txt
  - make docs-lint
after_success:
  cd securedrop/ && coveralls && cd ../  # cd back to repo root for srcclr run
addons:
  srcclr:
    debug: true
