---
build_ossec_deb_pkg_dependencies:
  - inotify-tools
  - libssl-dev
  - make
  - tar
  - unzip

ossec_server_hostname: ossec-server
ossec_version: 2.8.2
# Parent directory for performing build operations. All files related
# to build, including source tarball, will be created inside this dir.
build_path: /tmp/build

repo_src_path: "{{ build_path }}/ossec-{{ purpose }}"
ossec_build_dir: "{{ build_path }}/ossec-{{ purpose }}-{{ ossec_version }}-amd64"

# Destination on Ansible controller where built deb packages will be placed.
ossec_build_deb_package_local_dest_dir: "../../build/"
